name: Construction Paper

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core:2.9
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            --template=construction-paper/GitHub.html5 
            -V linkcolor:blue 
            -V fontsize=12pt 
            --mathjax 
            -f markdown_github+tex_math_dollars 
            -t html5
            construction-paper/Construction-Paper.md 
            -o construction-paper/Construction-Paper.html 
